interval=5

[wifi]
[ethernet]
label=
instance=wlan0
command=~/.i3blocks/network.sh
color=#00FF00
interval=10

[ethernet]
label=
instance=eth0
command=~/.i3blocks/network.sh
color=#00FF00
interval=10

[battery]
label=
command=~/.i3blocks/battery.sh
interval=60

[volume]
command=echo -n ' '; amixer get Master | grep -E -o '[0-9][0-9]?[0-9]?%'
interval=once
signal=1
# no interval, only check on SIGRTMIN+1

[date]
label=
command=date +"%B %e"
interval=3600

[time]
label=
command=date +"%l:%M"
interval=30
