interval=5

[wifi]
instance=wlan0
command=~/.i3blocks/network
color=#00FF00
interval=10

[ethernet]
instance=eth0
command=~/.i3blocks/network
color=#00FF00
interval=10

[cpu]
label=
command=~/.i3blocks/cpu_usage
interval=10

[memory]
label=
command=~/.i3blocks/memory
interval=30

[battery]
command=~/.i3blocks/battery
interval=60

[volume]
command=~/.i3blocks/volume
interval=once
signal=1
# no interval, only check on SIGRTMIN+1

[weather]
command=~/.i3blocks/darksky-weather
interval=600

[date]
label=
command=date +"%B %a. %e %l:%M"
interval=10
