# My thinkpad runs Artix which has no systemd to autostart these

#exec-once = pipewire
#exec-once = pipewire-pulse
#exec-once = wireplumber

## !! This was taken care of with dinit packages !!
## Had to install dinit-user-spawn for user dinit services then installed:
## - pipewire-dinit
## - pipewire-pulse-dinit
## - wireplumber-dinit
## Then enabled them one at a time with "dinitctl --user enable <service>"
