# hyprtoolkit.conf
# https://wiki.hypr.land/Hypr-Ecosystem/hyprtoolkit/
# Colors sourced from ~/.config/waybar/gruvbox.css

background = 0xFF1d2021
base = 0xFF282828
alternate_base = 0xFF3c3836
text = 0xFFebdbb2
bright_text = 0xFFfbf1c7
accent = 0xFF8ec07c
accent_secondary = 0xFF83a598

font_family = Sans Serif
font_family_monospace = monospace
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

icon_theme =

rounding_large = 10
rounding_small = 5
