#!/bin/sh
# Copyright (C) 2016 Ning Sun <sunng@about.me>
# Copyright (C) 2016 Carson Evans <me@carsonevans.ca>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# README:
#
# This script will get your city/country (based on your ip) address and
# get weather information for that location.
#
# This script requires a environment variable "OWM_API_KEY" to be set
# to a API key generated at openweathermap.org/api

APPID=$OWM_API_KEY
L_DATA=$(curl -s http://ip-api.com/json)
CITY=$(echo $L_DATA | jq -r ".city")
COUNTRY=$(echo $L_DATA | jq -r ".countryCode")

W_DATA=$(curl -s "http://api.openweathermap.org/data/2.5/weather?APPID=$APPID&q=$CITY,$COUNTRY&units=metric")
TEMP=$(echo $W_DATA | jq -r ".main.temp")
WEATHER=$(echo $W_DATA | jq -r ".weather[0].main")

# TODO: Show moon/sun versions of things depending on time of day
case $WEATHER in
    "Clear"*)
        WEATHER=
        ;;
    "Mist"*)
        WEATHER=
        ;;
    "Fog"*)
        WEATHER=
        ;;
    "Clouds"*)
        WEATHER=
        ;;
    "Rain"*)
        WEATHER=
        ;;
    "Snow"*)
        WEATHER=
        ;;
    "Thunderstorm"*)
        WEATHER=
        ;;
esac

echo "$WEATHER $CITY $TEMP°C"
echo "$CITY $TEMP°C"
