#!/bin/sh
# Copyright (C) 2016 Carson Evans <me@carsonevans.ca>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


status="$(amixer get Master | tail -n1 | awk '{print $6}' | grep -E -o '[a-z][a-z]')"
volume="$(amixer get Master | tail -n1 | awk '{print $5}' | grep -E -o '[0-9][0-9]?[0-9]?')"

if [ "$status" != "on" ] || [ "$volume" = "0" ]; then
	label=""
else
	label=""
fi

echo "$label $volume%"
echo "$label $volume%"
[ $status != "on" ] && echo "#FFAE00" || echo # Change color if muted
