#!/bin/sh
# Copyright (C) 2016 Carson Evans <me@carsonevans.ca>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# README:
#
# This script will get your city/country (based on your ip) address and
# get weather information for that location.
#
# This script requires a environment variable "WUNDERGROUND_KEY" to be set
# to a API key generated at https://www.wunderground.com/weather/api

API_KEY=$WUNDERGROUND_KEY
L_DATA=$(curl -s http://ip-api.com/json)
LAT=$(echo $L_DATA | jq -r ".lat")
LONG=$(echo $L_DATA | jq -r ".lon")
CITY=$(echo $L_DATA | jq -r ".city")

W_DATA=$(curl -s "http://api.wunderground.com/api/$API_KEY/conditions/q/$LAT,$LONG.json")
TEMP=$(echo $W_DATA | jq -r ".current_observation.temp_c")
WEATHER=$(echo $W_DATA | jq -r ".current_observation.weather")

# TODO: Show moon/sun versions of things depending on time of day
case $WEATHER in
    "Clear")
        WEATHER=
        ;;
    "Mist")
        WEATHER=
        ;;
    "Fog")
        WEATHER=
        ;;
    "Clouds"|"Overcast")
        WEATHER=
        ;;
    "Rain")
        WEATHER=
        ;;
    "Snow")
        WEATHER=
        ;;
    "Thunderstorm")
        WEATHER=
        ;;
esac

echo "$WEATHER $CITY $TEMP°C"
echo "$CITY $TEMP°C"